# Generated by Django 5.2.7 on 2025-10-04 05:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('approved', 'Tasdiqlangan'), ('not_confirmed', 'Tasdiqlanmadi'), ('group', 'Grupada')], default='not_confirmed', max_length=30)),
                ('admistrator', models.CharField(max_length=100)),
            ],
        ),
    ]
