# Generated by Django 5.2.7 on 2025-10-04 06:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='created_ad',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
