# Generated by Django 5.2.7 on 2025-10-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students_created_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='role',
            field=models.CharField(default='student', max_length=50),
        ),
    ]
