# Generated by Django 5.2.7 on 2025-10-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groups_group_time'),
        ('students', '0004_alter_students_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='students', to='groups.groups'),
        ),
    ]
