# Generated by Django 5.2.7 on 2025-10-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_students_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='about_student',
            field=models.TextField(blank=True, default=''),
        ),
    ]
