# Generated by Django 5.2.7 on 2025-10-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admistrators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_users',
            name='profile_img',
            field=models.FileField(default='media/profile.png', upload_to='media/profile_images'),
        ),
    ]
