# Generated by Django 5.2.7 on 2025-10-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admistrators', '0002_admin_users_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_users',
            name='profile_img',
        ),
    ]
