# Generated by Django 5.2.7 on 2025-10-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admistrators', '0003_remove_admin_users_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_users',
            name='profile_img',
            field=models.FileField(default='profile.png', upload_to='media/profile_images'),
        ),
    ]
