# Generated by Django 5.2.7 on 2025-10-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teachers_direction_teachers_firs_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='firs_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='teachers',
            name='role',
            field=models.CharField(default='teacher', max_length=50),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
