# Generated by Django 5.2.7 on 2025-10-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_rename_firs_name_teachers_first_name_teachers_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
