# Generated by Django 5.2.7 on 2025-10-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='group_price',
            field=models.IntegerField(default=0),
        ),
    ]
