# Generated by Django 5.2.7 on 2025-10-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groups_group_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='group_time',
            field=models.CharField(default='Dushanba,Chorshanba,Juma 14:00-16:00'),
        ),
    ]
