# Generated by Django 5.2.7 on 2025-10-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groups_group_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('inactive', 'Tugagan')], default='active', max_length=30),
        ),
    ]
