# Generated by Django 5.2.7 on 2025-10-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_groups_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='hwo_created',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
