# Generated by Django 5.2.7 on 2025-10-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_users',
            name='role',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
